package helpers

const (
	SUCCESS_CODE = 200
	FAIL_CODE    = 4000

	ILLEGAL_FAIL_CODE = 4002
	FAIL_PARAMS_CODE  = 4003
	CAPTCHA_FAIL_CODE = 4004

	// 登录相关
	LOGIN_FATL_CODE              = 5000
	USERNAME_PASSWD_ERROR_CODE   = 5001
	REPEAT_LOGIN_FAIL_CODE       = 5002
	TOKEN_FATL_CODE              = 5003
	TOKEN_FATL_OVERDUE_CODE      = 5004
	LOGIN_TOKEN_UPDATE_FATL_CODE = 5005
	USER_PROHIBIT_CODE           = 5006

	// 配置中心相关
	CONFIGURATION_PROJECT_NAME_FAIL_CODE          = 6000
	CONFIGURATION_ADD_PROJECT_FAIL_CODE           = 6001
	CONFIGURATION_EDIT_PROJECT_FAIL_CODE          = 6002
	CONFIGURATION_DEL_PROJECT_FAIL_CODE           = 6003
	CONFIGURATION_NAMESPACE_NAME_FAIL_CODE        = 6004
	CONFIGURATION_NAMESPACE_EDIT_FAIL_CODE        = 6005
	CONFIGURATION_DEL_NAMESPACE_FAIL_CODE         = 6006
	CONFIGURATION_PROJECT_NAME_REPEAT_FAIL_CODE   = 6007
	CONFIGURATION_NAMEPSACE_NAME_REPEAT_FAIL_CODE = 6008

	// etcd相关
	ETCD_SERVER_EXISTENCE_CODE      = 7000
	ETCD_SERVER_INIT_CODE           = 7001
	ETCD_SERVER_NOTE_EXISTENCE_CODE = 7002
	ETCD_SERVER_NOTE_CODE           = 7003

	// 配置中心节点配置
	CONFIGURATION_NODE_CONF_NAME_FAIL_CODE   = 8000
	CONFIGURATION_DEL_NODE_CONF_FAIL_CODE    = 8001
	CONFIGURATION_EDIT_NODE_CONF_FAIL_CODE   = 8002
	CONFIGURATION_NODE_CONF_ONLINE_NODE_CODE = 8003

	// 配置中心节点
	CONFIGURATION_NODE_ONLINE_DEL_FATL_CODE = 9000

	// 修改密码
	CHANGE_PASSWD_IDENTICAL_FAIL_CODE = 10000
	CHANGE_PASSWD_EMPTY_FAIL_CODE     = 10001
	CHANGE_PASSWD_FAIL_CODE           = 10002

	USERNAME_EXISTENCE_CODE      = 11000
	USERNAME_TO_PASSWD_FAIL_CODE = 11001

	TASK_CRONTAB_ANALYSIS_FAIL_CODE = 12000
	TASK_NAME_FAIL_CODE             = 12001
	TASK_CMD_FAIL_CODE              = 12002
	TASK_OVERTIME_FAIL_CODE         = 12003
	TASK_FAIL_NUM_CODE              = 12004
	TASK_FAIL_RETRY_TIME_CODE       = 12005
	TASK_NOTICE_FAIL_CODE           = 12006
	TASK_KEYWORD_NOTICE_FAIL_CODE   = 12007
	TASK_NODE_ONLINE_DEL_FATL_CODE  = 12008
)
